### PR TITLE
Lowercase repository name due Docker (#118)

### PR DESCRIPTION
**Pull request by adpe**
Hey @McPringle

I've introduced a regression within PR https://github.com/McPringle/apus/pull/110. This should fix the issue, as we need the repository name to be lowercase.

This will close issue #118.

Cheers
Adrian

### CODE REVIEW

**Comment by McPringle** [comment]
Thank you very much for checking this out. Do we really need another step for it? If it works, it might be better overall to just add the `@L` in the last step.

**Comment by McPringle** [comment]
Btw., could you please consider to sign-off your commits in the future? It's easy to do that. Just add `Signed-off-by: Author Name <authoremail@example.com>` to your commit message. If you use IntelliJ IDEA, there is a `Sign-off commit` checkbox in the top right of the commit dialog. Using git at the command line, is just adding a `-s` to it: `git commit -s`

There is more about the signoff feature in this nice blog article: [Git signoff and signing like a champ](https://dev.to/janderssonse/git-signoff-and-signing-like-a-champ-41f3)

**Comment by adpe** [comment]
I like the other approach more, as it's more readable what happens and so you can't miss this bash annotation, if you will use the variable again and again. But it's okay like that.

Thanks also for the information about the sign-off, never used it until now. Will check it out for future cases.

Thanks for fixing the issue. Therefore, I'll close this PR.

**Comment by McPringle** [comment]
It didn't worked as expected, so I decided to use your solution. 😁

**Comment by adpe** [comment]
Ohh okay. I was too fast by closing it. 😁

Please feel free next time to reopen the PR and merge it immediately.

**Comment by McPringle** [comment]
I tried it but it was not possible because the correcponding branch has been deleted. :-)

**Comment by adpe** [comment]
Ahhh sorry for that one. I could restore it. But anyway thank you! 🙏🏻

**Pull request closed without merging**
