### PR TITLE
Fix some Java issues. Change completely the theme

### PR DESCRIPTION
**Pull request by jcgueriaud1**
I played a bit with the theme. I removed a lot of absolute positioning and used css variables. I think that will be easier to maintain.

It's completely different but updating the color shouldn't be an issue.

I also changed the way to import CSS. (CssImport is not recommended when you are using a theme).

Feel free to cherry pick what you want.

image

image

It's also working in dark theme (you need to add `theme="dark"` manually to test it on the html tag)

### CODE REVIEW

**Comment by McPringle** [comment]
Wow, you did a great job! I see some issues with your design changes: In my test data there is only one speaker for each session. In reality there are sometimes two or more speakers. In my test data the rooms have just one letter, in reality the room names are longer. Both, speakers and room information, might very likely not fit where you put them.

I committed a change where now the data is loaded from the real conference API and the date of the session is modified to today. Now the test data is real data and should be much better.

My CSS skills, well, could be improved. I had some issues with the size of the session elements and to get it working I did the "absolute" hack. There are only a few days left to the start of the conference and they need the output to fit exactly on a 1920x1080 screen.

The theme you applied looks pretty good as a "standard theme". I would go with "my" colours anyway, because these are the colours of the JavaLand conference logo.

I committed a lot of changes the last few hours before I noticed your PR, so a merge would be really hard. Anyway, I would like to learn from your contribution and tomorrow I'll spend some time to go through it line by line and copy, what I understand. So please be patient.

And again, thank you very much!

**Comment by jcgueriaud1** [comment]
I've updated the colors, all you need to change is here:
```
    --card-color: #84ddee;
    --card-footer-color: var(--lumo-shade-5pct);
    --body-color: #007e89;
    --social-color: #1aa3b1;
```

and the layout.

image

**Comment by McPringle** [comment]
I tried my best to incorporate your changes. Everything is committed to the main branch. This is what I got so far:

image

As you can see, most of your modifications work. But there are some issues I don't understand so far. Issues I need to solve next are:

- [ ] The session time is out of the frame now. I have trouble with the margins around session title and speaker.
- [ ] The first Mastodon post in the first column starts lower than in column two and three.
- [ ] The gap between the columns of the Mastodon posts is too huge and I can't figure out why.

I'll try again tomorrow when I've had a good night's sleep.

**Comment by McPringle** [comment]
Most of the PR was cherry-picked and merged to the `main` branch. Some modifications do not work (e.g. the footer containing all detail information: not enough room for speaker and room names).

**Pull request closed without merging**
